"""Regenerate src/sentier_brightway/sources.toml from the data repos' main branches.

Usage: uv run python scripts/pin_sources.py [--ref sentier-inventory=<sha> ...]

Set GH_TOKEN or GITHUB_TOKEN (e.g. `export GH_TOKEN=$(gh auth token)`) to authenticate
GitHub API requests if you hit the unauthenticated rate limit.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import urllib.request
from pathlib import Path

REPOS = {
    "sentier-inventory": ("sentier-dev/sentier-inventory", ("data/",), (".parquet", ".json")),
    "sentier-vocab": ("sentier-dev/sentier-vocab", ("data/elementary-flows/",), (".parquet",)),
    "sentier-methods": (
        "sentier-dev/sentier-methods",
        ("data/01-ef-3.1/",),
        (".parquet", ".json"),
    ),
    "sentier-mappings": ("sentier-dev/sentier-mappings", ("data/",), (".json",)),
}
OUT = Path(__file__).resolve().parents[1] / "src" / "sentier_brightway" / "sources.toml"


def _headers() -> dict[str, str]:
    headers = {"User-Agent": "sentier-brightway-pin"}
    token = os.environ.get("GH_TOKEN") or os.environ.get("GITHUB_TOKEN")
    if token:
        headers["Authorization"] = f"Bearer {token}"
    return headers


def _get(url: str) -> bytes:
    req = urllib.request.Request(url, headers=_headers())
    with urllib.request.urlopen(req, timeout=120) as resp:
        return resp.read()


def _head_sha(repo: str) -> str:
    return json.loads(_get(f"https://api.github.com/repos/{repo}/commits/main"))["sha"]


def _tree(repo: str, sha: str) -> list[str]:
    data = json.loads(_get(f"https://api.github.com/repos/{repo}/git/trees/{sha}?recursive=1"))
    return [t["path"] for t in data["tree"] if t["type"] == "blob"]


def _wanted(name: str, path: str, prefixes: tuple[str, ...], suffixes: tuple[str, ...]) -> bool:
    if not path.startswith(prefixes) or not path.endswith(suffixes):
        return False
    return name != "sentier-mappings" or "/bafu-2026-v1__ef-3.1/" in path


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--ref", action="append", default=[], help="name=<sha> override")
    args = parser.parse_args()
    overrides = dict(kv.split("=", 1) for kv in args.ref)
    blocks = []
    for name, (repo, prefixes, suffixes) in REPOS.items():
        sha = overrides.get(name) or _head_sha(repo)
        paths = [p for p in _tree(repo, sha) if _wanted(name, p, prefixes, suffixes)]
        lines = [f'[[source]]\nname = "{name}"\nrepo = "{repo}"\nref = "{sha}"\n[source.files]']
        for path in sorted(paths):
            digest = hashlib.sha256(
                _get(f"https://raw.githubusercontent.com/{repo}/{sha}/{path}")
            ).hexdigest()
            lines.append(f'"{path}" = "{digest}"')
            print(f"{name} {path} {digest[:12]}")
        blocks.append("\n".join(lines))
    header = (
        "# Generated by scripts/pin_sources.py. Do not edit by hand.\n"
        "# Refs are pinned commit SHAs (not `main`); regenerate with:\n"
        "#   uv run python scripts/pin_sources.py "
        "[--ref <name>=<sha> ...]\n\n"
    )
    OUT.write_text(header + "\n\n".join(blocks) + "\n")
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
