"""Regenerate src/sentier_brightway/sources.toml from the data repos' main branches.

Usage: uv run python scripts/pin_sources.py [--ref sentier-inventory=<sha> ...]

Set GH_TOKEN or GITHUB_TOKEN (e.g. `export GH_TOKEN=$(gh auth token)`) to authenticate
GitHub API requests if you hit the unauthenticated rate limit.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import sys
import urllib.error
import urllib.request
from datetime import datetime, timezone
from pathlib import Path

REPOS = {
    "sentier-inventory": ("sentier-dev/sentier-inventory", ("data/",), (".parquet", ".json")),
    "sentier-vocab": ("sentier-dev/sentier-vocab", ("data/elementary-flows/",), (".parquet",)),
    "sentier-methods": (
        "sentier-dev/sentier-methods",
        ("data/01-ef-3.1/",),
        (".parquet", ".json"),
    ),
    "sentier-mappings": ("sentier-dev/sentier-mappings", ("data/",), (".json",)),
}
OUT = Path(__file__).resolve().parents[1] / "src" / "sentier_brightway" / "sources.toml"


def _headers() -> dict[str, str]:
    headers = {"User-Agent": "sentier-brightway-pin"}
    token = os.environ.get("GH_TOKEN") or os.environ.get("GITHUB_TOKEN")
    if token:
        headers["Authorization"] = f"Bearer {token}"
    return headers


def _get(url: str) -> bytes:
    req = urllib.request.Request(url, headers=_headers())
    try:
        with urllib.request.urlopen(req, timeout=120) as resp:
            return resp.read()
    except urllib.error.HTTPError as exc:
        sys.exit(
            f"GitHub request failed ({exc.code} {exc.reason}) for {url}; set GH_TOKEN "
            "(e.g. `export GH_TOKEN=$(gh auth token)`) if you are rate-limited"
        )
    except urllib.error.URLError as exc:
        sys.exit(f"GitHub request failed for {url}: {exc.reason}")


def _head_sha(repo: str) -> str:
    return json.loads(_get(f"https://api.github.com/repos/{repo}/commits/main"))["sha"]


def _tree(repo: str, sha: str) -> list[str]:
    url = f"https://api.github.com/repos/{repo}/git/trees/{sha}?recursive=1"
    data = json.loads(_get(url))
    if data.get("truncated"):
        sys.exit(
            f"tree for {repo}@{sha} was truncated by the GitHub API ({url}); narrow the "
            "prefixes or fetch subtrees separately instead of trusting a partial listing"
        )
    return [t["path"] for t in data["tree"] if t["type"] == "blob"]


def _wanted(name: str, path: str, prefixes: tuple[str, ...], suffixes: tuple[str, ...]) -> bool:
    if not path.startswith(prefixes) or not path.endswith(suffixes):
        return False
    return name != "sentier-mappings" or "/bafu-2026-v1__ef-3.1/" in path


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--ref", action="append", default=[], help="name=<sha> override")
    args = parser.parse_args()
    overrides = dict(kv.split("=", 1) for kv in args.ref)
    blocks = []
    for name, (repo, prefixes, suffixes) in REPOS.items():
        override = overrides.get(name)
        note = None
        if override:
            sha = override
            head = _head_sha(repo)
            note = f"# {name}: --ref override (main HEAD was {head})"
        else:
            sha = _head_sha(repo)
        paths = [p for p in _tree(repo, sha) if _wanted(name, p, prefixes, suffixes)]
        lines = []
        if note:
            lines.append(note)
        lines.append(
            f'[[source]]\nname = "{name}"\nrepo = "{repo}"\nref = "{sha}"\n[source.files]'
        )
        for path in sorted(paths):
            digest = hashlib.sha256(
                _get(f"https://raw.githubusercontent.com/{repo}/{sha}/{path}")
            ).hexdigest()
            lines.append(f'"{path}" = "{digest}"')
            print(f"{name} {path} {digest[:12]}")
        blocks.append("\n".join(lines))
    generated = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    header = (
        "# Generated by scripts/pin_sources.py. Do not edit by hand.\n"
        f"# generated: {generated}\n"
        "# Refs are pinned commit SHAs (not `main`); regenerate with:\n"
        "#   uv run python scripts/pin_sources.py [--ref <name>=<sha> ...]\n\n"
    )
    OUT.write_text(header + "\n\n".join(blocks) + "\n", encoding="utf-8")
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
